[CommonSettings]
SourcePath=Content/Localization/MMO
DestinationPath=Content/Localization/MMO
ManifestName=MMO.manifest
ArchiveName=MMO.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=zh-Hans

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=Source/MMORPG
SearchDirectoryPaths=Plugins/MMOFramework/Source
FileNameFilters=*.h
FileNameFilters=*.cpp
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=Content/UI/*
IncludePathFilters=Content/Localization/ST_MMO.uasset
PackageFileNameFilters=*.uasset
ShouldGatherFromEditorOnlyData=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

; This report must share the actual Source/Assets gathering context above.
[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bConflictReport=true
ConflictReportName=MMO_Conflicts.txt
